export enum MessageName {
  PROPOSED_APPOINTMENT = 'proposedAppointment',
  BOOK_APPOINTMENT = 'bookingAppointment',
  CANCEL_APPOINTMENT = 'cancelAppointment',
  CONFIRM_IN_PERSON_APPOINTMENT = 'confirmInPersonAppointment',
  CONFIRM_VIRTUAL_APPOINTMENT_PHONE = 'confirmVirtualAppointmentPhone',
  CONFIRM_VIRTUAL_APPOINTMENT_VIDEO = 'confirmVirtualAppointmentVideo',
  CONFIRM_VIRTUAL_APPOINTMENT_CHAT = 'confirmVirtualAppointmentChat',
  REMINDER_IN_PERSON_APPOINTMENT = 'reminderInPersonAppointment',
  REMINDER_VIRTUAL_APPOINTMENT = 'reminderVirtualAppointment',
  CANCEL_APPOINTMENT_PRACTITIONER = 'cancelAppointmentPractitioner',
  CONFIRM_IN_PERSON_APPOINTMENT_PRACTITIONER = 'confirmInPersonAppointmentPractitioner',
  CONFIRM_VIRTUAL_APPOINTMENT_PHONE_PRACTITIONER = 'confirmVirtualAppointmentPhonePractitioner',
  CONFIRM_VIRTUAL_APPOINTMENT_VIDEO_PRACTITIONER = 'confirmVirtualAppointmentVideoPractitioner',
  CONFIRM_VIRTUAL_APPOINTMENT_CHAT_PRACTITIONER = 'confirmVirtualAppointmentChatPractitioner',
  NOTIFY_TENANT_APPOINTMENT = 'notifyTenantAppointment',
}
